---
title: "Creating maps and visualising spatial point data with Leaflet and Rayshader"
author: "Ronja Seitz"
date: "2025-03-10"
output: html_document
---

# **Load required packages**
At the beginning of the code: Load the packages which will be needed to import data and create maps.

```{r setup, message=FALSE, warning=FALSE}
library(terra)
library(sf)
library(leaflet)
library(ggplot2)
```


Download a digital elevation model from f.e. https://geodata.npolar.no/
Find bounding box by coyping points from toposvalbard.
```{r load data}
# input data
dem_path <- "C:/Users/ronja/Documents/EAGLE/Svalbard/Data/Basemap/NP_S0_DTM20/S0_DTM20.tif" #path to dem
points_path <- "C:/Users/ronja/Documents/EAGLE/Svalbard/larissa_sos/faeces_sampling_2023_2024_all_data_continuously_updated.csv" #path to point data as csv
ortho_path <- "C:/Users/ronja/Documents/EAGLE/Svalbard/Data/Basemap/NP_Satellitt_Svalbard_Raster_25833/NP_Satellitt_Svalbard_Raster_25833.jp2"

# load input data
dem_raster <- rast(dem_path) #read in dem using terra. Can be visualised with plot()
points_df <- read.csv(points_path) #read the csv file as dataframe. To show data: print()
ortho_raster <- rast(ortho_path) #read orthomosaic .jp2 file with rast()
```

```{r create bounding box to crop data to (here coordinates of bjorndalen)}
# Define UTM zone and bounding box (Example: UTM Zone 33N)
utm_zone <- 33  # Change based on your location
utm_crs <- paste0("+proj=utm +zone=", utm_zone, " +datum=WGS84 +units=m +no_defs")

# Define bounding box for bjorndalen in UTM (Easting, Northing) 
utm_bbox <- st_sfc(st_polygon(list(matrix(c(
  505000 , 8676038,  # Bottom-left (E, N)
  509000 , 8676038,  # Bottom-right (E, N)
  509000 , 8684990,  # Top-right (E, N)
  505000 , 8684990, # Top-left (E, N)
  505000 , 8676038  #close polygon
), ncol = 2, byrow = TRUE))), crs = utm_crs)
```

```{r crop and prepare data for visulisation}
#crop dem to bounding box and plot first map
dem_bjorndalen <- crop(dem_raster, utm_bbox)
plot(dem_bjorndalen) 
#change type to dataframe because this is used in ggplot
map_df <- as.data.frame(dem_bjorndalen, xy = T)
#rename row names to make it more intuitive
colnames(map_df) <- c("easting", "northing", "elev_m")

#crop orthomosaic to bjorndalen extent


# change type of points data to vector to be able to crop it to needed extent
spatial_vector <- vect(points_df, geom = c("utm_easting", "utm_northing"), crs = "EPSG:25833")
points_bjorndalen <- crop(spatial_vector, dem_bjorndalen)

plot(points_bjorndalen)

#change type back to dataframe because that is the input for ggplot
points_bjorndalen_df <- as.data.frame(points_bjorndalen, geom = "XY", xy = T)
points_df <- na.omit(points_bjorndalen_df) #clean df from na values
```

```{r plot map with ggplot and geom_raster and geom_points}
# create plots of bjorndalen dem
gg_map <- ggplot(data = map_df) +
  geom_raster(aes(x = easting, y = northing, fill = elev_m)) +
  scale_fill_viridis_c(option = "E") +
  theme_light() +
  theme(legend.position = "right") +
  labs(
    title = "DEM",
    x = "Easting",
    y = "Northing"
  ) +
  coord_sf(crs = st_crs(25833))

# add the points to the map
gg_map_points <- gg_map +
  geom_point(data = points_df,aes(x = x, y = y), color = "brown", size = 2)

gg_map_points
```